[package]
name = "sickle_ui_scaffold"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dev = ["bevy/dynamic_linking"]

[dependencies]
sickle_math = { path = "../sickle_math" }
sickle_macros = { path = "../sickle_macros" }

bevy = { version = "0.14.0-rc.4" }
bevy_reflect = { version = "0.14.0-rc.4" }
serde = { version = "1.0", features = ["derive"] }
